// <auto-generated />
using System;
using GrpcServer.ContextDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrpcServer.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrpcServer.Models.AirQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AH")
                        .HasColumnType("real");

                    b.Property<float>("C6H6_GT")
                        .HasColumnType("real");

                    b.Property<float>("CO_GT")
                        .HasColumnType("real");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NMHC_GT")
                        .HasColumnType("integer");

                    b.Property<int>("NO2_GT")
                        .HasColumnType("integer");

                    b.Property<int>("NOx_GT")
                        .HasColumnType("integer");

                    b.Property<int>("PT08_S1_CO")
                        .HasColumnType("integer");

                    b.Property<int>("PT08_S2_NMHC")
                        .HasColumnType("integer");

                    b.Property<int>("PT08_S3_NOx")
                        .HasColumnType("integer");

                    b.Property<int>("PT08_S4_NO2")
                        .HasColumnType("integer");

                    b.Property<int>("PT08_S5_O3")
                        .HasColumnType("integer");

                    b.Property<float>("RH")
                        .HasColumnType("real");

                    b.Property<float>("T")
                        .HasColumnType("real");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("air_quality");
                });
#pragma warning restore 612, 618
        }
    }
}
