// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package iot.rest.grpc;

/**
 * Protobuf type {@code AirDataQuality}
 */
public  final class AirDataQuality extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AirDataQuality)
    AirDataQualityOrBuilder {
  // Use AirDataQuality.newBuilder() to construct.
  private AirDataQuality(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AirDataQuality() {
    coGt_ = 0F;
    pt08S1Co_ = 0;
    nmhcGt_ = 0;
    c6H6Gt_ = 0F;
    pt08S2Nmhc_ = 0;
    noxGt_ = 0;
    pt08S3Nox_ = 0;
    no2Gt_ = 0;
    pt08S4No2_ = 0;
    pt08S5O3_ = 0;
    t_ = 0F;
    rh_ = 0F;
    ah_ = 0F;
    id_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AirDataQuality(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (date_ != null) {
              subBuilder = date_.toBuilder();
            }
            date_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(date_);
              date_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Duration.Builder subBuilder = null;
            if (time_ != null) {
              subBuilder = time_.toBuilder();
            }
            time_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(time_);
              time_ = subBuilder.buildPartial();
            }

            break;
          }
          case 29: {

            coGt_ = input.readFloat();
            break;
          }
          case 32: {

            pt08S1Co_ = input.readInt32();
            break;
          }
          case 40: {

            nmhcGt_ = input.readInt32();
            break;
          }
          case 53: {

            c6H6Gt_ = input.readFloat();
            break;
          }
          case 56: {

            pt08S2Nmhc_ = input.readInt32();
            break;
          }
          case 64: {

            noxGt_ = input.readInt32();
            break;
          }
          case 72: {

            pt08S3Nox_ = input.readInt32();
            break;
          }
          case 80: {

            no2Gt_ = input.readInt32();
            break;
          }
          case 88: {

            pt08S4No2_ = input.readInt32();
            break;
          }
          case 96: {

            pt08S5O3_ = input.readInt32();
            break;
          }
          case 109: {

            t_ = input.readFloat();
            break;
          }
          case 117: {

            rh_ = input.readFloat();
            break;
          }
          case 125: {

            ah_ = input.readFloat();
            break;
          }
          case 128: {

            id_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Airquality.internal_static_AirDataQuality_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Airquality.internal_static_AirDataQuality_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AirDataQuality.class, Builder.class);
  }

  public static final int DATE_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp date_;
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  public com.google.protobuf.Timestamp getDate() {
    return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
  }
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
    return getDate();
  }

  public static final int TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Duration time_;
  /**
   * <code>.google.protobuf.Duration time = 2;</code>
   */
  public boolean hasTime() {
    return time_ != null;
  }
  /**
   * <code>.google.protobuf.Duration time = 2;</code>
   */
  public com.google.protobuf.Duration getTime() {
    return time_ == null ? com.google.protobuf.Duration.getDefaultInstance() : time_;
  }
  /**
   * <code>.google.protobuf.Duration time = 2;</code>
   */
  public com.google.protobuf.DurationOrBuilder getTimeOrBuilder() {
    return getTime();
  }

  public static final int CO_GT_FIELD_NUMBER = 3;
  private float coGt_;
  /**
   * <code>float co_gt = 3;</code>
   */
  public float getCoGt() {
    return coGt_;
  }

  public static final int PT08_S1_CO_FIELD_NUMBER = 4;
  private int pt08S1Co_;
  /**
   * <code>int32 pt08_s1_co = 4;</code>
   */
  public int getPt08S1Co() {
    return pt08S1Co_;
  }

  public static final int NMHC_GT_FIELD_NUMBER = 5;
  private int nmhcGt_;
  /**
   * <code>int32 nmhc_gt = 5;</code>
   */
  public int getNmhcGt() {
    return nmhcGt_;
  }

  public static final int C6H6_GT_FIELD_NUMBER = 6;
  private float c6H6Gt_;
  /**
   * <code>float c6h6_gt = 6;</code>
   */
  public float getC6H6Gt() {
    return c6H6Gt_;
  }

  public static final int PT08_S2_NMHC_FIELD_NUMBER = 7;
  private int pt08S2Nmhc_;
  /**
   * <code>int32 pt08_s2_nmhc = 7;</code>
   */
  public int getPt08S2Nmhc() {
    return pt08S2Nmhc_;
  }

  public static final int NOX_GT_FIELD_NUMBER = 8;
  private int noxGt_;
  /**
   * <code>int32 nox_gt = 8;</code>
   */
  public int getNoxGt() {
    return noxGt_;
  }

  public static final int PT08_S3_NOX_FIELD_NUMBER = 9;
  private int pt08S3Nox_;
  /**
   * <code>int32 pt08_s3_nox = 9;</code>
   */
  public int getPt08S3Nox() {
    return pt08S3Nox_;
  }

  public static final int NO2_GT_FIELD_NUMBER = 10;
  private int no2Gt_;
  /**
   * <code>int32 no2_gt = 10;</code>
   */
  public int getNo2Gt() {
    return no2Gt_;
  }

  public static final int PT08_S4_NO2_FIELD_NUMBER = 11;
  private int pt08S4No2_;
  /**
   * <code>int32 pt08_s4_no2 = 11;</code>
   */
  public int getPt08S4No2() {
    return pt08S4No2_;
  }

  public static final int PT08_S5_O3_FIELD_NUMBER = 12;
  private int pt08S5O3_;
  /**
   * <code>int32 pt08_s5_o3 = 12;</code>
   */
  public int getPt08S5O3() {
    return pt08S5O3_;
  }

  public static final int T_FIELD_NUMBER = 13;
  private float t_;
  /**
   * <code>float t = 13;</code>
   */
  public float getT() {
    return t_;
  }

  public static final int RH_FIELD_NUMBER = 14;
  private float rh_;
  /**
   * <code>float rh = 14;</code>
   */
  public float getRh() {
    return rh_;
  }

  public static final int AH_FIELD_NUMBER = 15;
  private float ah_;
  /**
   * <code>float ah = 15;</code>
   */
  public float getAh() {
    return ah_;
  }

  public static final int ID_FIELD_NUMBER = 16;
  private int id_;
  /**
   * <code>int32 id = 16;</code>
   */
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (date_ != null) {
      output.writeMessage(1, getDate());
    }
    if (time_ != null) {
      output.writeMessage(2, getTime());
    }
    if (coGt_ != 0F) {
      output.writeFloat(3, coGt_);
    }
    if (pt08S1Co_ != 0) {
      output.writeInt32(4, pt08S1Co_);
    }
    if (nmhcGt_ != 0) {
      output.writeInt32(5, nmhcGt_);
    }
    if (c6H6Gt_ != 0F) {
      output.writeFloat(6, c6H6Gt_);
    }
    if (pt08S2Nmhc_ != 0) {
      output.writeInt32(7, pt08S2Nmhc_);
    }
    if (noxGt_ != 0) {
      output.writeInt32(8, noxGt_);
    }
    if (pt08S3Nox_ != 0) {
      output.writeInt32(9, pt08S3Nox_);
    }
    if (no2Gt_ != 0) {
      output.writeInt32(10, no2Gt_);
    }
    if (pt08S4No2_ != 0) {
      output.writeInt32(11, pt08S4No2_);
    }
    if (pt08S5O3_ != 0) {
      output.writeInt32(12, pt08S5O3_);
    }
    if (t_ != 0F) {
      output.writeFloat(13, t_);
    }
    if (rh_ != 0F) {
      output.writeFloat(14, rh_);
    }
    if (ah_ != 0F) {
      output.writeFloat(15, ah_);
    }
    if (id_ != 0) {
      output.writeInt32(16, id_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (date_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDate());
    }
    if (time_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTime());
    }
    if (coGt_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, coGt_);
    }
    if (pt08S1Co_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, pt08S1Co_);
    }
    if (nmhcGt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, nmhcGt_);
    }
    if (c6H6Gt_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, c6H6Gt_);
    }
    if (pt08S2Nmhc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, pt08S2Nmhc_);
    }
    if (noxGt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, noxGt_);
    }
    if (pt08S3Nox_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, pt08S3Nox_);
    }
    if (no2Gt_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, no2Gt_);
    }
    if (pt08S4No2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, pt08S4No2_);
    }
    if (pt08S5O3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, pt08S5O3_);
    }
    if (t_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(13, t_);
    }
    if (rh_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(14, rh_);
    }
    if (ah_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(15, ah_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, id_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AirDataQuality)) {
      return super.equals(obj);
    }
    AirDataQuality other = (AirDataQuality) obj;

    boolean result = true;
    result = result && (hasDate() == other.hasDate());
    if (hasDate()) {
      result = result && getDate()
          .equals(other.getDate());
    }
    result = result && (hasTime() == other.hasTime());
    if (hasTime()) {
      result = result && getTime()
          .equals(other.getTime());
    }
    result = result && (
        Float.floatToIntBits(getCoGt())
        == Float.floatToIntBits(
            other.getCoGt()));
    result = result && (getPt08S1Co()
        == other.getPt08S1Co());
    result = result && (getNmhcGt()
        == other.getNmhcGt());
    result = result && (
        Float.floatToIntBits(getC6H6Gt())
        == Float.floatToIntBits(
            other.getC6H6Gt()));
    result = result && (getPt08S2Nmhc()
        == other.getPt08S2Nmhc());
    result = result && (getNoxGt()
        == other.getNoxGt());
    result = result && (getPt08S3Nox()
        == other.getPt08S3Nox());
    result = result && (getNo2Gt()
        == other.getNo2Gt());
    result = result && (getPt08S4No2()
        == other.getPt08S4No2());
    result = result && (getPt08S5O3()
        == other.getPt08S5O3());
    result = result && (
        Float.floatToIntBits(getT())
        == Float.floatToIntBits(
            other.getT()));
    result = result && (
        Float.floatToIntBits(getRh())
        == Float.floatToIntBits(
            other.getRh()));
    result = result && (
        Float.floatToIntBits(getAh())
        == Float.floatToIntBits(
            other.getAh()));
    result = result && (getId()
        == other.getId());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
    }
    hash = (37 * hash) + CO_GT_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getCoGt());
    hash = (37 * hash) + PT08_S1_CO_FIELD_NUMBER;
    hash = (53 * hash) + getPt08S1Co();
    hash = (37 * hash) + NMHC_GT_FIELD_NUMBER;
    hash = (53 * hash) + getNmhcGt();
    hash = (37 * hash) + C6H6_GT_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getC6H6Gt());
    hash = (37 * hash) + PT08_S2_NMHC_FIELD_NUMBER;
    hash = (53 * hash) + getPt08S2Nmhc();
    hash = (37 * hash) + NOX_GT_FIELD_NUMBER;
    hash = (53 * hash) + getNoxGt();
    hash = (37 * hash) + PT08_S3_NOX_FIELD_NUMBER;
    hash = (53 * hash) + getPt08S3Nox();
    hash = (37 * hash) + NO2_GT_FIELD_NUMBER;
    hash = (53 * hash) + getNo2Gt();
    hash = (37 * hash) + PT08_S4_NO2_FIELD_NUMBER;
    hash = (53 * hash) + getPt08S4No2();
    hash = (37 * hash) + PT08_S5_O3_FIELD_NUMBER;
    hash = (53 * hash) + getPt08S5O3();
    hash = (37 * hash) + T_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getT());
    hash = (37 * hash) + RH_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getRh());
    hash = (37 * hash) + AH_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getAh());
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AirDataQuality parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AirDataQuality parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AirDataQuality parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AirDataQuality parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AirDataQuality parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AirDataQuality parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AirDataQuality parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AirDataQuality parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AirDataQuality parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AirDataQuality parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AirDataQuality parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AirDataQuality parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AirDataQuality prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AirDataQuality}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AirDataQuality)
      AirDataQualityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Airquality.internal_static_AirDataQuality_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Airquality.internal_static_AirDataQuality_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AirDataQuality.class, Builder.class);
    }

    // Construct using iot.rest.grpc.AirDataQuality.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (dateBuilder_ == null) {
        date_ = null;
      } else {
        date_ = null;
        dateBuilder_ = null;
      }
      if (timeBuilder_ == null) {
        time_ = null;
      } else {
        time_ = null;
        timeBuilder_ = null;
      }
      coGt_ = 0F;

      pt08S1Co_ = 0;

      nmhcGt_ = 0;

      c6H6Gt_ = 0F;

      pt08S2Nmhc_ = 0;

      noxGt_ = 0;

      pt08S3Nox_ = 0;

      no2Gt_ = 0;

      pt08S4No2_ = 0;

      pt08S5O3_ = 0;

      t_ = 0F;

      rh_ = 0F;

      ah_ = 0F;

      id_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Airquality.internal_static_AirDataQuality_descriptor;
    }

    public AirDataQuality getDefaultInstanceForType() {
      return AirDataQuality.getDefaultInstance();
    }

    public AirDataQuality build() {
      AirDataQuality result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AirDataQuality buildPartial() {
      AirDataQuality result = new AirDataQuality(this);
      if (dateBuilder_ == null) {
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      if (timeBuilder_ == null) {
        result.time_ = time_;
      } else {
        result.time_ = timeBuilder_.build();
      }
      result.coGt_ = coGt_;
      result.pt08S1Co_ = pt08S1Co_;
      result.nmhcGt_ = nmhcGt_;
      result.c6H6Gt_ = c6H6Gt_;
      result.pt08S2Nmhc_ = pt08S2Nmhc_;
      result.noxGt_ = noxGt_;
      result.pt08S3Nox_ = pt08S3Nox_;
      result.no2Gt_ = no2Gt_;
      result.pt08S4No2_ = pt08S4No2_;
      result.pt08S5O3_ = pt08S5O3_;
      result.t_ = t_;
      result.rh_ = rh_;
      result.ah_ = ah_;
      result.id_ = id_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AirDataQuality) {
        return mergeFrom((AirDataQuality)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AirDataQuality other) {
      if (other == AirDataQuality.getDefaultInstance()) return this;
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      if (other.hasTime()) {
        mergeTime(other.getTime());
      }
      if (other.getCoGt() != 0F) {
        setCoGt(other.getCoGt());
      }
      if (other.getPt08S1Co() != 0) {
        setPt08S1Co(other.getPt08S1Co());
      }
      if (other.getNmhcGt() != 0) {
        setNmhcGt(other.getNmhcGt());
      }
      if (other.getC6H6Gt() != 0F) {
        setC6H6Gt(other.getC6H6Gt());
      }
      if (other.getPt08S2Nmhc() != 0) {
        setPt08S2Nmhc(other.getPt08S2Nmhc());
      }
      if (other.getNoxGt() != 0) {
        setNoxGt(other.getNoxGt());
      }
      if (other.getPt08S3Nox() != 0) {
        setPt08S3Nox(other.getPt08S3Nox());
      }
      if (other.getNo2Gt() != 0) {
        setNo2Gt(other.getNo2Gt());
      }
      if (other.getPt08S4No2() != 0) {
        setPt08S4No2(other.getPt08S4No2());
      }
      if (other.getPt08S5O3() != 0) {
        setPt08S5O3(other.getPt08S5O3());
      }
      if (other.getT() != 0F) {
        setT(other.getT());
      }
      if (other.getRh() != 0F) {
        setRh(other.getRh());
      }
      if (other.getAh() != 0F) {
        setAh(other.getAh());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AirDataQuality parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AirDataQuality) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp date_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public boolean hasDate() {
      return dateBuilder_ != null || date_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public com.google.protobuf.Timestamp getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public Builder setDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public Builder setDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public Builder mergeDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (date_ != null) {
          date_ =
            com.google.protobuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
        } else {
          date_ = value;
        }
        onChanged();
      } else {
        dateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = null;
        onChanged();
      } else {
        date_ = null;
        dateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateBuilder() {
      
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }

    private com.google.protobuf.Duration time_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> timeBuilder_;
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public boolean hasTime() {
      return timeBuilder_ != null || time_ != null;
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public com.google.protobuf.Duration getTime() {
      if (timeBuilder_ == null) {
        return time_ == null ? com.google.protobuf.Duration.getDefaultInstance() : time_;
      } else {
        return timeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public Builder setTime(com.google.protobuf.Duration value) {
      if (timeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        time_ = value;
        onChanged();
      } else {
        timeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public Builder setTime(
        com.google.protobuf.Duration.Builder builderForValue) {
      if (timeBuilder_ == null) {
        time_ = builderForValue.build();
        onChanged();
      } else {
        timeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public Builder mergeTime(com.google.protobuf.Duration value) {
      if (timeBuilder_ == null) {
        if (time_ != null) {
          time_ =
            com.google.protobuf.Duration.newBuilder(time_).mergeFrom(value).buildPartial();
        } else {
          time_ = value;
        }
        onChanged();
      } else {
        timeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public Builder clearTime() {
      if (timeBuilder_ == null) {
        time_ = null;
        onChanged();
      } else {
        time_ = null;
        timeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public com.google.protobuf.Duration.Builder getTimeBuilder() {
      
      onChanged();
      return getTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    public com.google.protobuf.DurationOrBuilder getTimeOrBuilder() {
      if (timeBuilder_ != null) {
        return timeBuilder_.getMessageOrBuilder();
      } else {
        return time_ == null ?
            com.google.protobuf.Duration.getDefaultInstance() : time_;
      }
    }
    /**
     * <code>.google.protobuf.Duration time = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
        getTimeFieldBuilder() {
      if (timeBuilder_ == null) {
        timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                getTime(),
                getParentForChildren(),
                isClean());
        time_ = null;
      }
      return timeBuilder_;
    }

    private float coGt_ ;
    /**
     * <code>float co_gt = 3;</code>
     */
    public float getCoGt() {
      return coGt_;
    }
    /**
     * <code>float co_gt = 3;</code>
     */
    public Builder setCoGt(float value) {
      
      coGt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float co_gt = 3;</code>
     */
    public Builder clearCoGt() {
      
      coGt_ = 0F;
      onChanged();
      return this;
    }

    private int pt08S1Co_ ;
    /**
     * <code>int32 pt08_s1_co = 4;</code>
     */
    public int getPt08S1Co() {
      return pt08S1Co_;
    }
    /**
     * <code>int32 pt08_s1_co = 4;</code>
     */
    public Builder setPt08S1Co(int value) {
      
      pt08S1Co_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pt08_s1_co = 4;</code>
     */
    public Builder clearPt08S1Co() {
      
      pt08S1Co_ = 0;
      onChanged();
      return this;
    }

    private int nmhcGt_ ;
    /**
     * <code>int32 nmhc_gt = 5;</code>
     */
    public int getNmhcGt() {
      return nmhcGt_;
    }
    /**
     * <code>int32 nmhc_gt = 5;</code>
     */
    public Builder setNmhcGt(int value) {
      
      nmhcGt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nmhc_gt = 5;</code>
     */
    public Builder clearNmhcGt() {
      
      nmhcGt_ = 0;
      onChanged();
      return this;
    }

    private float c6H6Gt_ ;
    /**
     * <code>float c6h6_gt = 6;</code>
     */
    public float getC6H6Gt() {
      return c6H6Gt_;
    }
    /**
     * <code>float c6h6_gt = 6;</code>
     */
    public Builder setC6H6Gt(float value) {
      
      c6H6Gt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float c6h6_gt = 6;</code>
     */
    public Builder clearC6H6Gt() {
      
      c6H6Gt_ = 0F;
      onChanged();
      return this;
    }

    private int pt08S2Nmhc_ ;
    /**
     * <code>int32 pt08_s2_nmhc = 7;</code>
     */
    public int getPt08S2Nmhc() {
      return pt08S2Nmhc_;
    }
    /**
     * <code>int32 pt08_s2_nmhc = 7;</code>
     */
    public Builder setPt08S2Nmhc(int value) {
      
      pt08S2Nmhc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pt08_s2_nmhc = 7;</code>
     */
    public Builder clearPt08S2Nmhc() {
      
      pt08S2Nmhc_ = 0;
      onChanged();
      return this;
    }

    private int noxGt_ ;
    /**
     * <code>int32 nox_gt = 8;</code>
     */
    public int getNoxGt() {
      return noxGt_;
    }
    /**
     * <code>int32 nox_gt = 8;</code>
     */
    public Builder setNoxGt(int value) {
      
      noxGt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nox_gt = 8;</code>
     */
    public Builder clearNoxGt() {
      
      noxGt_ = 0;
      onChanged();
      return this;
    }

    private int pt08S3Nox_ ;
    /**
     * <code>int32 pt08_s3_nox = 9;</code>
     */
    public int getPt08S3Nox() {
      return pt08S3Nox_;
    }
    /**
     * <code>int32 pt08_s3_nox = 9;</code>
     */
    public Builder setPt08S3Nox(int value) {
      
      pt08S3Nox_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pt08_s3_nox = 9;</code>
     */
    public Builder clearPt08S3Nox() {
      
      pt08S3Nox_ = 0;
      onChanged();
      return this;
    }

    private int no2Gt_ ;
    /**
     * <code>int32 no2_gt = 10;</code>
     */
    public int getNo2Gt() {
      return no2Gt_;
    }
    /**
     * <code>int32 no2_gt = 10;</code>
     */
    public Builder setNo2Gt(int value) {
      
      no2Gt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 no2_gt = 10;</code>
     */
    public Builder clearNo2Gt() {
      
      no2Gt_ = 0;
      onChanged();
      return this;
    }

    private int pt08S4No2_ ;
    /**
     * <code>int32 pt08_s4_no2 = 11;</code>
     */
    public int getPt08S4No2() {
      return pt08S4No2_;
    }
    /**
     * <code>int32 pt08_s4_no2 = 11;</code>
     */
    public Builder setPt08S4No2(int value) {
      
      pt08S4No2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pt08_s4_no2 = 11;</code>
     */
    public Builder clearPt08S4No2() {
      
      pt08S4No2_ = 0;
      onChanged();
      return this;
    }

    private int pt08S5O3_ ;
    /**
     * <code>int32 pt08_s5_o3 = 12;</code>
     */
    public int getPt08S5O3() {
      return pt08S5O3_;
    }
    /**
     * <code>int32 pt08_s5_o3 = 12;</code>
     */
    public Builder setPt08S5O3(int value) {
      
      pt08S5O3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pt08_s5_o3 = 12;</code>
     */
    public Builder clearPt08S5O3() {
      
      pt08S5O3_ = 0;
      onChanged();
      return this;
    }

    private float t_ ;
    /**
     * <code>float t = 13;</code>
     */
    public float getT() {
      return t_;
    }
    /**
     * <code>float t = 13;</code>
     */
    public Builder setT(float value) {
      
      t_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float t = 13;</code>
     */
    public Builder clearT() {
      
      t_ = 0F;
      onChanged();
      return this;
    }

    private float rh_ ;
    /**
     * <code>float rh = 14;</code>
     */
    public float getRh() {
      return rh_;
    }
    /**
     * <code>float rh = 14;</code>
     */
    public Builder setRh(float value) {
      
      rh_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float rh = 14;</code>
     */
    public Builder clearRh() {
      
      rh_ = 0F;
      onChanged();
      return this;
    }

    private float ah_ ;
    /**
     * <code>float ah = 15;</code>
     */
    public float getAh() {
      return ah_;
    }
    /**
     * <code>float ah = 15;</code>
     */
    public Builder setAh(float value) {
      
      ah_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float ah = 15;</code>
     */
    public Builder clearAh() {
      
      ah_ = 0F;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 16;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 16;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 16;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:AirDataQuality)
  }

  // @@protoc_insertion_point(class_scope:AirDataQuality)
  private static final AirDataQuality DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AirDataQuality();
  }

  public static AirDataQuality getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AirDataQuality>
      PARSER = new com.google.protobuf.AbstractParser<AirDataQuality>() {
    public AirDataQuality parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AirDataQuality(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AirDataQuality> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AirDataQuality> getParserForType() {
    return PARSER;
  }

  public AirDataQuality getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

