// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package iot.rest.grpc;

public interface AirDataQualityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirDataQuality)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>.google.protobuf.Duration time = 2;</code>
   */
  boolean hasTime();
  /**
   * <code>.google.protobuf.Duration time = 2;</code>
   */
  com.google.protobuf.Duration getTime();
  /**
   * <code>.google.protobuf.Duration time = 2;</code>
   */
  com.google.protobuf.DurationOrBuilder getTimeOrBuilder();

  /**
   * <code>float co_gt = 3;</code>
   */
  float getCoGt();

  /**
   * <code>int32 pt08_s1_co = 4;</code>
   */
  int getPt08S1Co();

  /**
   * <code>int32 nmhc_gt = 5;</code>
   */
  int getNmhcGt();

  /**
   * <code>float c6h6_gt = 6;</code>
   */
  float getC6H6Gt();

  /**
   * <code>int32 pt08_s2_nmhc = 7;</code>
   */
  int getPt08S2Nmhc();

  /**
   * <code>int32 nox_gt = 8;</code>
   */
  int getNoxGt();

  /**
   * <code>int32 pt08_s3_nox = 9;</code>
   */
  int getPt08S3Nox();

  /**
   * <code>int32 no2_gt = 10;</code>
   */
  int getNo2Gt();

  /**
   * <code>int32 pt08_s4_no2 = 11;</code>
   */
  int getPt08S4No2();

  /**
   * <code>int32 pt08_s5_o3 = 12;</code>
   */
  int getPt08S5O3();

  /**
   * <code>float t = 13;</code>
   */
  float getT();

  /**
   * <code>float rh = 14;</code>
   */
  float getRh();

  /**
   * <code>float ah = 15;</code>
   */
  float getAh();

  /**
   * <code>int32 id = 16;</code>
   */
  int getId();
}
