// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package iot.rest.grpc;

public final class Airquality {
  private Airquality() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirDataQuality_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirDataQuality_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020airquality.proto\032\036google/protobuf/dura" +
      "tion.proto\032\037google/protobuf/timestamp.pr" +
      "oto\032\033google/protobuf/empty.proto\"\024\n\006Data" +
      "Id\022\n\n\002id\030\001 \001(\005\"\313\002\n\016AirDataQuality\022(\n\004dat" +
      "e\030\001 \001(\0132\032.google.protobuf.Timestamp\022\'\n\004t" +
      "ime\030\002 \001(\0132\031.google.protobuf.Duration\022\r\n\005" +
      "co_gt\030\003 \001(\002\022\022\n\npt08_s1_co\030\004 \001(\005\022\017\n\007nmhc_" +
      "gt\030\005 \001(\005\022\017\n\007c6h6_gt\030\006 \001(\002\022\024\n\014pt08_s2_nmh" +
      "c\030\007 \001(\005\022\016\n\006nox_gt\030\010 \001(\005\022\023\n\013pt08_s3_nox\030\t" +
      " \001(\005\022\016\n\006no2_gt\030\n \001(\005\022\023\n\013pt08_s4_no2\030\013 \001(",
      "\005\022\022\n\npt08_s5_o3\030\014 \001(\005\022\t\n\001t\030\r \001(\002\022\n\n\002rh\030\016" +
      " \001(\002\022\n\n\002ah\030\017 \001(\002\022\n\n\002id\030\020 \001(\0052\314\001\n\nAirQual" +
      "ity\022)\n\013getDataById\022\007.DataId\032\017.AirDataQua" +
      "lity\"\000\0220\n\ncreateData\022\017.AirDataQuality\032\017." +
      "AirDataQuality\"\000\022/\n\ndeleteData\022\007.DataId\032" +
      "\026.google.protobuf.Empty\"\000\0220\n\nupdateData\022" +
      "\017.AirDataQuality\032\017.AirDataQuality\"\000B\021\n\ri" +
      "ot.rest.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_DataId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_AirDataQuality_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AirDataQuality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirDataQuality_descriptor,
        new java.lang.String[] { "Date", "Time", "CoGt", "Pt08S1Co", "NmhcGt", "C6H6Gt", "Pt08S2Nmhc", "NoxGt", "Pt08S3Nox", "No2Gt", "Pt08S4No2", "Pt08S5O3", "T", "Rh", "Ah", "Id", });
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
