// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: airquality.proto

package iot.rest.grpc;

public interface DataIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
